queue_rules:
 - name: default
   conditions: []

pull_request_rules:
  - name: Use merge queue
    conditions:
      - base=main
      - label=s:accepted
    actions:
      label:
        remove:
          - s:in-progress
          - s:review-needed
      queue:
        name: default
  - name: ask to resolve conflict
    conditions:
      - conflict
    actions:
        comment:
          message: This pull request is now in conflicts. Could you fix it @{{author}}? 🙏

