queue_rules:
 - name: default
   conditions: []

pull_request_rules:
  - name: Use merge queue
    conditions:
      - base=main
      - label=s:accepted
    actions:
      label:
        remove:
          - s:in-progress
          - s:review-needed
      queue:
        name: default
